package app.wheelstop.android.blindspot

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Golden-vector test for the open reimplementation of the blind-spot coefficient math.
 *
 * The fixture `resources/blindspot/golden.txt` was generated by running the ORIGINAL native
 * library (`libod.so`, the binary this Kotlin replaces) under an aarch64 emulator on random
 * inputs — so this asserts parity with the real thing, not merely internal consistency. Each
 * line is `in0..in10 | out0..out19`. Derivation and the emulator harness are documented in
 * docs/blindspot-coefficients.md.
 *
 * Tolerance is exact-to-float here because the fixture and this code both compute trig in
 * double precision and cast to float. On-device the original used single-precision
 * tanf/sincosf, which differs by at most a ULP — invisible in a sampler coefficient.
 */
class BsCoefficientsTest {

    private fun golden(): List<Pair<FloatArray, FloatArray>> =
        BsCoefficientsTest::class.java.getResourceAsStream("/blindspot/golden.txt")!!
            .bufferedReader().readLines()
            .filter { it.isNotBlank() }
            .map { line ->
                val (inS, outS) = line.split("|")
                val inp = inS.trim().split(Regex("\\s+")).map { it.toFloat() }.toFloatArray()
                val out = outS.trim().split(Regex("\\s+")).map { it.toFloat() }.toFloatArray()
                inp to out
            }

    @Test
    fun matchesTheOriginalBinaryOnGoldenVectors() {
        val vectors = golden()
        assertTrue("fixture should not be empty", vectors.isNotEmpty())
        var maxErr = 0f
        for ((inp, expected) in vectors) {
            val got = FloatArray(20)
            BsCoefficients.resolve(inp, got)
            for (i in 0 until 20) {
                val e = kotlin.math.abs(got[i] - expected[i])
                if (e > maxErr) maxErr = e
            }
        }
        assertEquals("max abs error vs the real native library", 0.0, maxErr.toDouble(), 1e-6)
    }

    @Test
    fun malformedInputZeroFills() {
        val out = FloatArray(20) { 7f }
        BsCoefficients.resolve(FloatArray(5), out)
        assertTrue("short input must zero-fill", out.all { it == 0f })
    }

    @Test
    fun alwaysReady() {
        assertTrue(BsCoefficients.isReady)
        assertTrue(BsCoefficients.tryLoadLibrary("/nonexistent"))
    }

    @Test
    fun out11UsesTheOriginalOneThirdConstant() {
        // 0x3eaaaa3b, not 1f/3f — a subtle but real difference the original embedded.
        val out = FloatArray(20)
        BsCoefficients.resolve(FloatArray(11) { if (it == 5) 0.6f else 0f }, out)
        assertEquals(0.6f * Float.fromBits(0x3eaaaa3b), out[11], 0f)
    }
}
