package app.wheelstop.android.config

import android.util.Log
import org.json.JSONObject
import java.io.File

/**
 * Single source of truth for Overdrive's settings backup / restore.
 *
 * ARCHITECTURE — one core, three surfaces (mirrors the OTA update feature):
 * the export/restore logic is defined ONLY here, inside the camera-daemon
 * process (UID 2000, the sole process that can atomic-rename in sticky
 * /data/local/tmp/). Every surface is a thin adapter that calls this via the
 * daemon's IPC commands (SurveillanceIpcServer EXPORT_CONFIG / REPLACE_CONFIG):
 *   - Web      → ConfigBackupApiHandler (runs in-process, calls directly)
 *   - App UI   → UnifiedConfigManager IPC client → REPLACE_CONFIG
 *   - Telegram → BackupCommandHandler → ctx.sendIpcCommand(19877, …)
 * Nothing is duplicated; the adapters are pure transport.
 *
 * SCOPE — SAME-DEVICE restore only (called out in the UI). Because the bundle
 * is restored onto the same head-unit/vehicle, the cross-device hazards
 * (vehicle-specific camera HAL ids, tunnel-token split-brain) do NOT apply, so
 * those keys are carried verbatim. The remaining hazards are write-path, not
 * data: see [applyBundle].
 *
 * SECRETS — the 3 device-bound encrypted credentials (bydCloud password,
 * navMap routing key, telegram bot token) are stored as their `ENC:` blobs and
 * the bundle ALSO snapshots the device-id file (.byd_device_id) that
 * CredentialCipher derives its key from. Restoring the DID first lets the
 * blobs decrypt again even after a factory reset. TRADEOFF: the bundle then
 * contains key material, so the export endpoint MUST stay LOCAL-mode + JWT
 * gated and the UI MUST warn the user to keep the file private.
 */
object ConfigBackupService {
    private const val TAG = "ConfigBackup"

    const val BUNDLE_FORMAT = "overdrive-config-bundle"
    const val BUNDLE_VERSION = 1
    // Bump when applyBundle's understood schema changes incompatibly. A bundle
    // with a HIGHER schemaVersion than this is refused (forward-incompatible).
    const val SCHEMA_VERSION = 1

    // CredentialCipher.DID_PATH — duplicated as a literal rather than exposing
    // it, to keep this class free of a crypto dependency. Must match
    // CredentialCipher.java:29.
    private const val DID_PATH = "/data/local/tmp/.byd_device_id"

    // Runtime/coordination keys that are meaningless or harmful to restore even
    // on the same device. Stripped on BOTH export and import (defence in depth
    // against a hand-edited bundle). Path form: "section.key".
    private val EPHEMERAL_KEYS = listOf(
        "navMap.clusterMapActive",   // daemon↔activity runtime flag; stale=ghost map
    )

    // Whole top-level keys never carried in a bundle.
    //  - updates: the OTA channel must stay whatever THIS install compiled with
    //    (restoring "alpha" into a stable build pulls alpha APKs).
    //  - lastModified / version: regenerated by the config layer on write.
    //  - configSeq: the monotonic write sequence is install-local durability
    //    state (UnifiedConfigManager). A restore must NEVER inject a foreign seq
    //    — that could wedge the highest-seq-wins recovery/promotion ordering.
    //    Stripped on export + skipped on import; the live config keeps its own
    //    seq and saveConfig bumps it past the prior value on write.
    private val EXCLUDED_SECTIONS = listOf("updates", "lastModified", "version", "configSeq")

    // Sections whose secret fields are device-bound `ENC:` blobs. If the DID
    // could NOT be restored (writeDid failed), overlaying these would replace
    // the user's CURRENTLY-WORKING credentials with blobs that can no longer
    // decrypt (key derives from the DID) — actively making things worse. In
    // that one case we skip them so the live credentials survive.
    private val CREDENTIAL_SECTIONS = listOf("bydCloud", "navMap", "telegram")

    // Recursion cap for [deepMergeInto] — guards against a pathological
    // hand-edited bundle with deeply nested objects. Real config nesting is
    // <= 2 levels (e.g. geocoding.recording.enabled), so 6 is generous.
    private const val MAX_MERGE_DEPTH = 6

    // Dotted paths whose direct CHILD objects are ATOMIC values (discriminated
    // unions / opaque records), NOT mergeable maps. deepMergeInto replaces such
    // a child wholesale instead of recursing into it — otherwise a child that
    // changed shape between export and the live config (e.g. a camera role that
    // switched from a panoramic_slice ref to a direct ref) would keep the
    // live-only variant field (a stale `slice` left beside a new `cameraId`),
    // producing a hybrid record. camera.roleMappings maps <role> → CameraSourceRef,
    // a "kind"-discriminated union (CameraSourceRef.toJson emits only the fields
    // for its kind), so each role value must be replaced atomically.
    private val ATOMIC_CHILD_PARENT_PATHS = setOf("camera.roleMappings")

    /**
     * Recursively overlay [incoming] onto [base], in place. For each key: if
     * BOTH sides hold a JSONObject, recurse (preserving live sub-keys the
     * bundle predates); otherwise the incoming value overrides. Beyond
     * [MAX_MERGE_DEPTH] it falls back to a wholesale put (depth-1 behaviour) so
     * a malicious deeply-nested bundle can't blow the stack.
     *
     * [path] is the dotted path of [base] (""/"camera"/"camera.roleMappings").
     * When [path] is in [ATOMIC_CHILD_PARENT_PATHS], each child is REPLACED
     * wholesale rather than merged, so discriminated-union records don't end up
     * with stale variant fields.
     *
     * Trade-off (by design): a sub-key the user DELETED post-export is NOT
     * removed by restore — additive-merge is the correct fix for the silent
     * sub-key LOSS this replaces; honouring deletes would require a tombstone
     * the bundle format doesn't carry.
     */
    private fun deepMergeInto(base: JSONObject, incoming: JSONObject, path: String = "", depth: Int = 0) {
        val mergeChildrenAtomically = path in ATOMIC_CHILD_PARENT_PATHS
        val keys = incoming.keys()
        while (keys.hasNext()) {
            val k = keys.next()
            val iv = incoming.get(k)
            val bv = base.opt(k)
            if (iv is JSONObject && bv is JSONObject && depth < MAX_MERGE_DEPTH
                    && !mergeChildrenAtomically) {
                deepMergeInto(bv, iv, if (path.isEmpty()) k else "$path.$k", depth + 1)
            } else {
                base.put(k, iv)
            }
        }
    }

    // ==================== EXPORT ====================

    /**
     * Build a backup bundle from the live config + the device-id file.
     * Runs in the daemon process. Returns a JSONObject ready to serialise.
     *
     * WHAT THE BUNDLE CONTAINS (so the privacy surface is explicit):
     *  - Every unified-config section EXCEPT [EXCLUDED_SECTIONS] and the
     *    [EPHEMERAL_KEYS]. That includes credential sections whose secret
     *    fields are stored as `ENC:` blobs — bydCloud (username + login/sign
     *    keys + password), navMap.routingApiKey, telegram.botToken. The
     *    username/identity fields are NOT encrypted. This is acceptable ONLY
     *    because the feature is same-device and the export endpoints are
     *    LOCAL-mode + JWT gated; the UI warns the file holds credentials.
     *  - The device-id (.byd_device_id) so the `ENC:` blobs stay decryptable
     *    after a factory reset (CredentialCipher binds its key to the DID).
     * WHAT IT DOES NOT CONTAIN:
     *  - SafeLocation home/work GPS — stored in the separate file
     *    /data/local/tmp/safe_locations.json, deliberately not bundled.
     *  - Tunnel tokens (.zrok/.tailscale), the OTA channel, runtime flags.
     */
    @JvmStatic
    @JvmOverloads
    fun buildBundle(appVersion: String, deviceModel: String, nowMs: Long,
                    includeTrips: Boolean = false): JSONObject {
        // Fresh read so a just-saved peer write is included.
        val live = UnifiedConfigManager.forceReload()
        val unified = JSONObject(live.toString())   // deep copy; don't mutate cache

        for (sec in EXCLUDED_SECTIONS) unified.remove(sec)
        stripEphemeral(unified)

        val categories = org.json.JSONArray().put("settings")

        val manifest = JSONObject()
            .put("format", BUNDLE_FORMAT)
            .put("bundleVersion", BUNDLE_VERSION)
            .put("schemaVersion", SCHEMA_VERSION)
            .put("appVersion", appVersion)
            .put("deviceModel", deviceModel)
            .put("fingerprint", safeFingerprint())
            .put("exportedAtMs", nowMs)
            .put("sameDeviceOnly", true)

        val bundle = JSONObject()
            .put("manifest", manifest)
            .put("settings", JSONObject().put("unified", unified))

        // Snapshot the DID so the ENC: secrets remain decryptable after a
        // factory reset. Best-effort: absent DID just means secrets fall back
        // to re-entry on a reset (they still decrypt on a non-reset restore).
        readDid()?.let { bundle.put("did", it) }

        // Opt-in trips category (stats only — no telemetry files). The trips DB
        // lives in the daemon; pulled via the manager. Best-effort: if the
        // manager/DB isn't up, the category is simply omitted.
        if (includeTrips) {
            try {
                val tam = app.wheelstop.android.daemon.CameraDaemon.getTripAnalyticsManager()
                val db = tam?.database
                if (db != null && db.isAvailable) {
                    val trips = db.exportTripsJson()
                    bundle.put("trips", trips)
                    categories.put("trips")
                    Log.i(TAG, "Bundle includes ${trips.length()} trips (stats-only)")
                } else {
                    Log.w(TAG, "Trips requested but DB unavailable; omitting category")
                }
            } catch (e: Exception) {
                Log.w(TAG, "Trips export skipped: ${e.message}")
            }
        }
        manifest.put("categories", categories)

        Log.i(TAG, "Built backup bundle (appVersion=$appVersion, model=$deviceModel, " +
            "didIncluded=${bundle.has("did")})")
        return bundle
    }

    // ==================== IMPORT ====================

    data class ApplyResult(val success: Boolean, val message: String, val warnings: List<String>)

    /**
     * Validate a bundle WITHOUT writing anything. Used by the import-preview
     * endpoint so the UI can show compatibility warnings + a confirm step.
     */
    @JvmStatic
    fun validateBundle(bundle: JSONObject, currentAppVersion: String, currentModel: String): ApplyResult {
        val warnings = ArrayList<String>()
        val manifest = bundle.optJSONObject("manifest")
            ?: return ApplyResult(false, "Not an Overdrive backup (missing manifest).", warnings)
        if (BUNDLE_FORMAT != manifest.optString("format")) {
            return ApplyResult(false, "Unrecognised file format.", warnings)
        }
        if (manifest.optInt("schemaVersion", Int.MAX_VALUE) > SCHEMA_VERSION) {
            return ApplyResult(false,
                "This backup is from a newer Overdrive version. Update the app first.", warnings)
        }
        val unifiedForCheck = bundle.optJSONObject("settings")?.optJSONObject("unified")
            ?: return ApplyResult(false, "Backup contains no settings.", warnings)
        // Every config section is a JSON object. Reject a hand-edited/corrupt
        // bundle that carries a scalar where a section object belongs (e.g.
        // {"surveillance": 123}) — overlaying it would replace the live section
        // object with a scalar and make every getJSONObject("surveillance")
        // reader throw. (Top-level scalars like version/lastModified are excluded
        // from the overlay anyway, but the bundle shouldn't contain unified-level
        // scalar sections at all.)
        val badKeys = unifiedForCheck.keys().asSequence().filter { k ->
            !EXCLUDED_SECTIONS.contains(k) && unifiedForCheck.opt(k) !is JSONObject
        }.toList()
        if (badKeys.isNotEmpty()) {
            return ApplyResult(false,
                "Backup is malformed (invalid section: ${badKeys.first()}).", warnings)
        }
        // Same-device advisories (non-blocking — user confirms).
        val bundleModel = manifest.optString("deviceModel", "")
        if (bundleModel.isNotEmpty() && bundleModel != currentModel) {
            warnings.add("Backup was made on a different vehicle model ($bundleModel vs $currentModel). " +
                "Camera/blind-spot calibration may not match.")
        }
        // Firmware change breaks credential decryption regardless of the DID:
        // CredentialCipher's key = SHA256(salt:DID:Build.FINGERPRINT), so a
        // changed fingerprint derives a different key and the ENC: secrets
        // decrypt to "" (silently). Warn whenever the fingerprint differs —
        // the earlier "&& !bundle.has(did)" guard was backwards (on a same-
        // device restore the DID is ALWAYS present, so the warning never fired
        // for the very case that needs it).
        // Warn only about credentials the bundle CARRIES that actually fail to
        // decrypt under the current key — mirroring apply-time, which gates on a
        // real test-decrypt (NOT on a bare fingerprint change). A stable-key
        // blob decrypts fine post-OTA, so a fingerprint change alone must not
        // scare the user about credentials that will restore correctly.
        val carriedUndecryptable = CREDENTIAL_SECTIONS.filter {
            sectionHasEncryptedSecret(unifiedForCheck, it) &&
                !sectionSecretDecryptsClean(unifiedForCheck, it)
        }
        if (carriedUndecryptable.isNotEmpty()) {
            val names = carriedUndecryptable.joinToString(", ") { credentialLabel(it) }
            val bundleFp = manifest.optString("fingerprint", "")
            val fpHint = if (bundleFp.isNotEmpty() && bundleFp != safeFingerprint())
                " (device firmware changed since this backup)" else ""
            warnings.add("These saved credentials could not be decrypted$fpHint and may " +
                "need re-entering: $names.")
        }
        val bundleApp = manifest.optString("appVersion", "")
        if (bundleApp.isNotEmpty() && bundleApp != currentAppVersion) {
            warnings.add("Backup is from app version $bundleApp (current $currentAppVersion).")
        }
        // NOTE: a DID mismatch (bundle.did != current .byd_device_id) is
        // deliberately NOT warned here. Unlike a fingerprint change (which we
        // can't undo), applyBundle RESTORES the bundle's DID before writing the
        // config, so the ENC: secrets decrypt correctly afterwards — a preview
        // warning would be a false alarm. The only genuine failure is writeDid()
        // itself failing during apply; that is surfaced as a runtime warning in
        // applyBundle's skip-and-warn path, not predicted here.
        return ApplyResult(true, "Backup looks valid.", warnings)
    }

    /**
     * Apply a bundle. DAEMON-ONLY caller (UID 2000) — this performs the atomic
     * whole-config write. Order matters:
     *   1. Restore the DID file FIRST so the imported ENC: secrets decrypt.
     *   2. Strip excluded/ephemeral keys + preserve THIS install's OTA channel.
     *   3. Atomic whole-object save via UnifiedConfigManager.saveConfig
     *      (tmp+rename, .bak mirror, single notifyListeners("all") cascade).
     *
     * R8 (corruption latch): saveConfig refuses if a prior load latched
     * corruption. We forceReload() first; a clean load clears the latch. If it
     * stays latched the on-disk file is genuinely unparseable — we surface that
     * rather than silently failing.
     */
    @JvmStatic
    fun applyBundle(bundle: JSONObject, currentAppVersion: String, currentModel: String): ApplyResult {
        val validation = validateBundle(bundle, currentAppVersion, currentModel)
        if (!validation.success) return validation
        // validateBundle returns an immutable-intent list; copy so we can append
        // a runtime warning (DID restore failure) discovered during apply.
        val warnings = ArrayList(validation.warnings)

        // 1. DID first so the imported ENC: secrets decrypt post-restore.
        // Snapshot the PRIOR DID before overwriting so we can roll it back if the
        // config save later fails: otherwise we'd be left split-brained — the
        // NEW device-id on disk but the OLD config blobs (keyed to the old DID),
        // which would silently decrypt to "" on next boot even though the restore
        // reported failure. didWasRestored records whether we actually changed it.
        var didOk = true   // true if no DID to restore OR the restore succeeded
        var didWasRestored = false
        val priorDid: String? = if (bundle.has("did")) readDid() else null
        if (bundle.has("did")) {
            val did = bundle.optString("did", "")
            if (did.isNotEmpty()) {
                if (writeDid(did)) {
                    didWasRestored = true
                    Log.i(TAG, "Restored device-id from bundle")
                } else {
                    didOk = false
                    Log.w(TAG, "Could not restore device-id; will skip credential sections")
                }
            }
        }

        val incoming = bundle.optJSONObject("settings")?.optJSONObject("unified")
            ?: return ApplyResult(false, "Backup contains no settings.", warnings)

        // Authoritative test: actually PROVE the bundle's ENC: credential blobs
        // decrypt under the now-current key before overlaying them. This is the
        // SOLE gate — we no longer pre-skip on a fingerprint change. Since
        // CredentialCipher.decrypt tries the STABLE (fingerprint-free) key
        // first, a backup written under the stable key decrypts fine AFTER an
        // OTA, so a firmware change must NOT by itself drop the credentials
        // (that was the OTA-loss strand the stable key exists to prevent). A
        // genuinely-undecryptable blob (legacy fingerprint-bound + fingerprint
        // changed, or corrupt/tampered) still fails this test → "" → skip, so
        // we never overwrite live credentials with dead ciphertext.
        val secretsDecryptable = if (didOk) bundleSecretsDecrypt(incoming) else false
        if (didOk && !secretsDecryptable) {
            Log.w(TAG, "Bundled secrets did not decrypt under the restored key; " +
                "skipping credential sections")
        }
        // fpChanged is kept only for the human-readable warning reason below —
        // it no longer drives the skip decision.
        val fpChanged = run {
            val fp = bundle.optJSONObject("manifest")?.optString("fingerprint", "") ?: ""
            fp.isNotEmpty() && fp != safeFingerprint()
        }
        val skipSections =
            if (didOk && secretsDecryptable) emptySet()
            else CREDENTIAL_SECTIONS.toSet()

        // Warn ONLY about credential sections that were ACTUALLY skipped AND that
        // the bundle genuinely carried an ENC: secret for — so we never name a
        // token the backup didn't contain (false-positive) nor stay silent when
        // one was dropped (false-negative). Grounds the warning in what really
        // happened, not a binary flag.
        if (skipSections.isNotEmpty()) {
            val dropped = skipSections.filter { sectionHasEncryptedSecret(incoming, it) }
            if (dropped.isNotEmpty()) {
                val names = dropped.joinToString(", ") { credentialLabel(it) }
                // Name the actual root cause. The skip is now driven solely by
                // a failed test-decrypt; a fingerprint change only matters when
                // it's WHY a legacy-key blob no longer decrypts, so mention it
                // as context rather than as the gate.
                val reason = when {
                    !didOk -> "the device key could not be restored"
                    fpChanged -> "the saved credentials could not be decrypted " +
                        "(device firmware changed since this backup)"
                    else -> "the saved credentials could not be decrypted"
                }
                warnings.add("Because $reason, these saved credentials were not restored " +
                    "and your current ones were kept — re-enter if needed: $names.")
            }
        }

        // 2+3. Merge + persist UNDER the cross-process config lock. This is the
        // same OS advisory lock updateSection/updateValues hold for their whole
        // read-modify-write; without it a peer daemon JVM's section write
        // landing between our fresh-read and our save would be silently dropped
        // (the documented stale-snapshot lost-update invariant). forceReload()
        // INSIDE the lock gives a guaranteed-fresh base; the lock is reentrant,
        // so saveConfig's own locked paths nest harmlessly.
        val ok = UnifiedConfigManager.runUnderConfigLock {
            // Fresh under-lock base: a COMPLETE config (every seeded section +
            // THIS install's OTA channel) and clears any corruption latch (R8).
            val current = UnifiedConfigManager.forceReload()
            val toWrite = JSONObject(current.toString())

            // Per-KEY deep merge (not per-section put): when an OLDER backup is
            // restored onto a NEWER app, a section may have gained keys the
            // bundle predates (e.g. surveillance.detectBike). A wholesale
            // section put would drop those; a per-key merge keeps the live
            // section's keys and only overrides the ones the bundle carries —
            // matching updateSection's semantics. EXCLUDED_SECTIONS are skipped
            // (never import the OTA channel — R6).
            val sectionKeys = incoming.keys()
            while (sectionKeys.hasNext()) {
                val k = sectionKeys.next()
                if (EXCLUDED_SECTIONS.contains(k)) continue
                if (skipSections.contains(k)) continue   // DID-failed: keep live creds
                val incomingVal = incoming.get(k)
                val baseVal = toWrite.opt(k)
                if (incomingVal is JSONObject && baseVal is JSONObject) {
                    // DEEP merge, not depth-1. The previous one-level loop did
                    // baseVal.put(ik, incomingVal.get(ik)) — when an inner value
                    // was ITSELF an object (geocoding.recording/surveillance/
                    // advanced, oemDashcam.surveillance, camera.roleMappings) it
                    // wholesale-REPLACED the live nested object, silently
                    // dropping sub-keys the (older) bundle predated. Recursing
                    // preserves live nested sub-keys while still overriding the
                    // ones the bundle carries — matching the stated intent.
                    // Pass the section name as the path root so atomic-child
                    // paths (camera.roleMappings) replace rather than merge.
                    deepMergeInto(baseVal, incomingVal, k)
                    toWrite.put(k, baseVal)
                } else {
                    toWrite.put(k, incomingVal)
                }
            }
            stripEphemeral(toWrite)   // drop runtime-only keys the bundle may carry

            // Defensive: EXCLUDED_SECTIONS are skipped on overlay so they keep
            // the live values, but if the live base somehow lacked one (e.g. a
            // first-boot config with no "updates" yet), make sure it isn't left
            // absent — restore it from current (no-op if current also lacked it;
            // getUpdateChannel then falls back to the compiled channel safely).
            for (sec in EXCLUDED_SECTIONS) {
                if (!toWrite.has(sec) && current.has(sec)) toWrite.put(sec, current.get(sec))
            }

            // A bundle taken BEFORE the trips default-ON change carries
            // tripAnalytics.enabled=false, while the per-key merge above keeps the
            // live enabledDefaultMigrated=true. ensureDefaults would then skip
            // both the seed and the one-shot flip (it sees both keys present), so
            // restoring an old backup would silently turn trip recording off
            // FOREVER with no way for the migration to re-fire. Drop the marker
            // whenever the bundle supplied an explicit `enabled`, so the one-shot
            // upgrade re-evaluates against the restored value exactly once.
            try {
                val restoredTrips = toWrite.optJSONObject("tripAnalytics")
                val bundleTrips = incoming.optJSONObject("tripAnalytics")
                if (restoredTrips != null && bundleTrips != null && bundleTrips.has("enabled")) {
                    restoredTrips.remove("enabledDefaultMigrated")
                }
            } catch (e: Exception) {
                Log.w(TAG, "trips migration-marker reset failed: ${e.message}")
            }

            // Backfill any key the current app expects but neither the live
            // config nor the bundle carried, so we never PERSIST an incomplete
            // config (saveConfig doesn't run applyDefaults; loadConfig only
            // re-defaults on the geocoding-migration path). Idempotent.
            UnifiedConfigManager.ensureDefaults(toWrite)

            // force=true: bypass the corruption latch. `toWrite` is a COMPLETE,
            // already-validated user config (validateBundle passed + merged onto a
            // fresh forceReload base + ensureDefaults), NOT a defaults-merge — so
            // the latch's "don't clobber recoverable settings with defaults" guard
            // does not apply. Critically, RESTORE is the recovery path FOR config
            // corruption: if the live file is corrupt and both .bak copies are
            // unusable, the latch is set and the forceReload above can't clear it,
            // so a plain saveConfig would return false and block the very action
            // meant to fix the corruption ("Could not write settings"). Forcing
            // writes the good bytes and clears the latch on success.
            val saved = UnifiedConfigManager.saveConfig(toWrite, /* force = */ true)
            // Refresh the in-memory cache to the bytes we just wrote WHILE STILL
            // HOLDING the lock. Doing the final forceReload outside the lock left
            // a window where a peer daemon's section write could land between our
            // save and our reload, so the cache would reflect the peer's bytes
            // (harmless for data, but the IPC reply's freshness contract wants
            // our write visible). Inside the lock the reload is serialized.
            if (saved) UnifiedConfigManager.forceReload()
            saved
        }
        if (!ok) {
            // The config save failed but we may have ALREADY overwritten the DID
            // file. Roll the DID back to its prior value so we don't leave the
            // new device-id paired with the old config's blobs (which would
            // decrypt to "" on next boot — silent credential loss despite a
            // reported failure). Restores atomicity: failed save ⇒ DID unchanged.
            if (didWasRestored && priorDid != null) {
                if (writeDid(priorDid)) Log.w(TAG, "Config save failed; rolled device-id back")
                else Log.e(TAG, "Config save failed AND device-id rollback failed; " +
                    "credentials may need re-entry")
            }
            return ApplyResult(false,
                "Could not write settings. The config may be locked or damaged — " +
                "try again after restarting the camera service.", warnings)
        }
        // Trips category (opt-in, stats-only). Replayed AFTER the config save so
        // a settings restore never depends on the trips DB being up. Idempotent
        // + deduped inside importTripsJson, so a partial/duplicate import is
        // safe. Runs outside the config file lock — it's a different DB with its
        // own connection serialization. Best-effort: a trips failure never fails
        // the settings restore (which already succeeded above).
        val tripsArr = bundle.optJSONArray("trips")
        if (tripsArr != null && tripsArr.length() > 0) {
            try {
                val tam = app.wheelstop.android.daemon.CameraDaemon.getTripAnalyticsManager()
                val db = tam?.database
                if (db != null && db.isAvailable) {
                    val n = db.importTripsJson(tripsArr)
                    Log.i(TAG, "Restored $n trips from bundle")
                    if (n > 0) warnings.add("Imported $n trip(s) into your history " +
                        "(detailed per-trip telemetry is not included in backups).")
                } else {
                    warnings.add("Trip history could not be restored — the trips service " +
                        "wasn't ready. Restart the camera daemon and re-import.")
                }
            } catch (e: Exception) {
                Log.w(TAG, "Trips import failed: ${e.message}")
                warnings.add("Trip history could not be restored (${e.message}).")
            }
        }

        Log.i(TAG, "Backup applied (warnings=${warnings.size})")
        return ApplyResult(true, "Settings restored.", warnings)
    }

    // ==================== helpers ====================

    /** True if the named section in [unified] carries an `ENC:` credential blob.
     *  Lets the skip-warning name only the credentials the bundle ACTUALLY held,
     *  rather than a blanket "3 tokens" message. */
    private fun sectionHasEncryptedSecret(unified: JSONObject, section: String): Boolean {
        val obj = unified.optJSONObject(section) ?: return false
        return obj.toString().contains("\"ENC:")
    }

    /**
     * Verify the bundle's credential sections actually decrypt under the
     * current device key. Finds the first `ENC:` blob across the credential
     * sections and attempts to decrypt it. Returns:
     *   - true  if there are no ENC: blobs (nothing to lose), or one decrypts
     *           to real plaintext
     *   - false if an ENC: blob is present but decrypt does NOT yield usable
     *           plaintext (wrong key, or a malformed/too-short blob)
     *
     * NOTE on the failure check: CredentialCipher.decrypt returns "" on a
     * key/MAC mismatch, BUT for a malformed blob (Base64 payload shorter than
     * IV+tag) it returns the ORIGINAL "ENC:…" string unchanged rather than "".
     * So "non-empty" alone is NOT proof of success — a returned value that is
     * still an ENC: blob (or byte-identical to the input) means decryption did
     * not actually happen. Treat both as failure so a corrupted/tampered bundle
     * can't pass validation and overwrite working credentials with garbage.
     * Cheap (one AES-GCM open) and only runs on restore.
     */
    private fun bundleSecretsDecrypt(unified: JSONObject): Boolean {
        // Check EVERY ENC: blob across ALL credential sections, not just the
        // first — a bundle could carry a valid bydCloud blob and a tampered
        // navMap/telegram one; an early return on the first success would let
        // the corrupt later blob through. Any blob that fails to yield real
        // plaintext fails the whole validation (→ skip credentials, keep live).
        for (section in CREDENTIAL_SECTIONS) {
            if (!sectionSecretDecryptsClean(unified, section)) return false
        }
        return true   // no ENC: blobs, or all of them decrypted cleanly
    }

    /**
     * True if every ENC: blob in [section] decrypts to real plaintext under the
     * current device key (or the section carries none). Mirrors the per-blob
     * success test in [bundleSecretsDecrypt]. Used by the validate-preview so a
     * fingerprint change alone doesn't warn about credentials that will in fact
     * restore (stable-key blobs decrypt fine post-OTA).
     */
    private fun sectionSecretDecryptsClean(unified: JSONObject, section: String): Boolean {
        val obj = unified.optJSONObject(section) ?: return true
        val keys = obj.keys()
        while (keys.hasNext()) {
            val v = obj.opt(keys.next())
            if (v is String &&
                app.wheelstop.android.byd.cloud.crypto.CredentialCipher.isEncrypted(v)) {
                val ok = try {
                    val out = app.wheelstop.android.byd.cloud.crypto.CredentialCipher.decrypt(v)
                    // Success ONLY if we got real plaintext: non-empty, not the
                    // original blob echoed back, and no longer ENC:-tagged.
                    out.isNotEmpty() && out != v &&
                        !app.wheelstop.android.byd.cloud.crypto.CredentialCipher.isEncrypted(out)
                } catch (e: Exception) {
                    false
                }
                if (!ok) return false
            }
        }
        return true
    }

    /** Human label for a credential section, for the re-entry warning. */
    private fun credentialLabel(section: String): String = when (section) {
        "bydCloud" -> "BYD Cloud login"
        "navMap"   -> "navigation API key"
        "telegram" -> "Telegram bot token"
        else        -> section
    }

    private fun stripEphemeral(root: JSONObject) {
        for (path in EPHEMERAL_KEYS) {
            val dot = path.indexOf('.')
            if (dot <= 0) continue
            val section = path.substring(0, dot)
            val key = path.substring(dot + 1)
            root.optJSONObject(section)?.remove(key)
        }
    }

    private fun safeFingerprint(): String = try {
        android.os.Build.FINGERPRINT ?: "unknown"
    } catch (e: Exception) { "unknown" }

    // Read the DID exactly as CredentialCipher does — FIRST LINE only, trimmed.
    // CredentialCipher.readDid uses BufferedReader.readLine().trim(), so reading
    // the whole file here could capture a trailing line the cipher ignores,
    // making the snapshot diverge from the key-derivation input. firstLine keeps
    // the two byte-identical.
    private fun readDid(): String? = try {
        val f = File(DID_PATH)
        if (f.exists()) f.readText().lineSequence().firstOrNull()?.trim()?.ifEmpty { null } else null
    } catch (e: Exception) {
        Log.w(TAG, "DID read failed: ${e.message}"); null
    }

    /**
     * Write the DID world-readable. This is INTENTIONAL and required, NOT a
     * leak: CredentialCipher reads .byd_device_id cross-UID (app 10xxx AND
     * daemon 2000) to derive its key; if the file isn't world-readable the
     * app-side decrypt falls back to a sentinel DID and every credential reads
     * as "" (see the credentialcipher-did-perms invariant). So unlike a secret
     * temp file, the DID's *final* state is world-readable by design — there is
     * no "tighten after write" race here: a freshly created file is at most
     * owner-only during the gap (MORE restrictive, not less), and an existing
     * file is already world-readable. The setReadable call LOOSENS to the
     * required end state; ordering write-vs-chmod doesn't change exposure. The
     * DID is a device identifier, not the secret — the encrypted blobs it keys
     * already sit at 0666 in wheelstop_config.json under the same on-device
     * threat model.
     */
    private fun writeDid(value: String): Boolean = try {
        val f = File(DID_PATH)
        // Persist only the FIRST line, trimmed — exactly what CredentialCipher
        // (readLine().trim()) will read back for key derivation. A bundle whose
        // "did" field somehow carried embedded newlines can't then create a file
        // whose whole-text snapshot differs from the cipher's first-line read.
        val single = value.lineSequence().firstOrNull()?.trim() ?: ""
        f.writeText(single)
        f.setReadable(true, false)
        f.setWritable(true, false)
        true
    } catch (e: Exception) {
        Log.w(TAG, "DID write failed: ${e.message}"); false
    }
}
